Various small updates.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -120,7 +120,8 @@ SVN_REPOSS=(kroc-srcpkg ccsp cputimer-utils mkoccdeps occ21 ilibr tranx86 kroc l
 ALL_PKGS="$CCSP_SRC $MKOCCDEPS_SRC $CPUTIMERUTILS_SRC $OCC21_SRC $ILIBR_SRC $TRANX86_SRC $KROC_SRC $KROCIF_SRC $INMOSLIBS_SRC $BSCLIB_SRC $BSCLIB_EXAMPLES_SRC \
 	$COURSE_SRC $COURSE_EXAMPLES_SRC $COURSE_ANSWERS_SRC $SYNCS_SRC $SYNCS_EXAMPLES_SRC \
 	$DYNPROC_SRC $DYNPROC_EXAMPLES_SRC $UDC_SRC $UDC_EXAMPLES_SRC $CIF_SRC $CIF_EXAMPLES_SRC $CGTESTS_SRC $DEMO_BAR_SRC $DEMO_GAME_SRC \
-	$SDLRASTER_SRC $SDLRASTER_EXAMPLES_SRC $PONY_SRC $PONY_EXAMPLES_SRC $DOC_SRC $CONTRIB_SRC $OCCAMDOC_SRC"
+	$SDLRASTER_SRC $SDLRASTER_EXAMPLES_SRC $PONY_SRC $PONY_EXAMPLES_SRC $DOC_SRC $CONTRIB_SRC $OCCAMDOC_SRC \
+	$OCCSDL_SRC $OCCSDL_EXAMPLES_SRC $OCCADE_SRC $OCCADE_EXAMPLES_SRC"
 FAILABLE_PKGS="$SDLRASTER_SRC $SDLRASTER_EXAMPLES_SRC $CONTRIB_MOA_LIBSRC $CONTRIB_MOA_EXAMPLES $OCCSDL_SRC $OCCSDL_EXAMPLES_SRC $OCCADE_SRC $OCCADE_EXAMPLES_SRC"
 
 
@@ -609,7 +610,7 @@ configure_pkg ()
 			if [ -f .success ]; then
 				rm .success
 			else
-				printf 'error while configuring in %s' "$3" | tee -a "$DUMPOUT" 1>&2
+				printf 'error while configuring in %s\n' "$3" | tee -a "$DUMPOUT" 1>&2
 				deferred_install_error
 				return 1
 			fi
