Updated for new installation structure.  Removed some auto-generated files.  Added new configuration file for KRoC, which defines the various paths.  Can specify with "kroc -C kroc.conf".

diff --git a/kroc.in b/kroc.in
--- a/kroc.in
+++ b/kroc.in
@@ -1,5 +1,6 @@
 #! /bin/sh
 
+#{{{  make sure we have bash
 if [ "$BASH_VERSION" = "" ]; then
 	BASH=
 	# search for "bash" in the PATH environment
@@ -17,6 +18,9 @@ if [ "$BASH_VERSION" = "" ]; then
 
 	exec $BASH "$0" "$@"
 fi
+
+
+#}}}
 
 # should be in bash when we get here
 
@@ -42,28 +46,54 @@ fi
 #
 
 # If this file has the name "kroc.in" then it is a template for the kroc
-# driver program; to generate the actual kroc script, run
-# "./configure --prefix=<KRoC-path>" in the src/kroc-* directory
+# driver program; to generate the actual kroc script, use:
+#     ./build --force-configure configure-kroc make-kroc [install-kroc]
+# in the KRoC source tree
 #
-# Note: you shouldn't really do this yourself -- the build script will
-# handle it.
 
-# Only ever calls echo and sed UNIX programs (via `s)
-SED=@SED@
+#{{{  set $SED and $progname
+SED="@SED@"
 
 progname=$(printf '%s' "$0" | $SED 's/^.*\///')
 
-KROC=@KROC@
+#}}}
+#{{{  first task is to find the configuration file
+KROC_CONFIGDIR="@KROC_CONFIGDIR@"
+KROCCONFIG=""
+
+#
+#  search-order for KRoC configuration is:
+#	.kroc.conf
+#	<config-dir>/{kroc.conf,.kroc.conf}
+#	/etc/kroc.conf
+#	/usr/local/etc/kroc.conf
+#
+
+if [ -r "./.kroc.conf" ]; then
+	KROCCONFIG="./.kroc_conf"
+elif [ -r "$KROC_CONFIGDIR/kroc.conf" ]; then
+	KROCCONFIG="$KROC_CONFIGDIR/kroc.conf"
+elif [ -r "$KROC_CONFIGDIR/.kroc.conf" ]; then
+	KROCCONFIG="$KROC_CONFIGDIR/.kroc.conf"
+elif [ -r "/etc/kroc.conf" ]; then
+	KROCCONFIG="/etc/kroc.conf"
+elif [ -r "/usr/local/etc/kroc.conf" ]; then
+	KROCCONFIG="/usr/local/etc/kroc.conf"
+fi
+
+
+#}}}
+#{{{  setup various variables
+
 CC=@CC@
 
 # Only the 'kroc' program need be in the users path
-PATH=$KROC/bin:$PATH
+#PATH=$KROC/bin:$PATH
 
-package_version=@VERSION@
-dversion='1.5'
-host_canonical=@KROC_CANONICAL_TARGET@
-host_os=@KROC_HOST_OS@
-host_cpu=@KROC_HOST_CPU@
+package_version="@VERSION@"
+dversion='2.0'
+host_canonical="@KROC_CANONICAL_TARGET@"
+host_cpu="@KROC_HOST_CPU@"
 # -kf : use fast CCSP interface
 octranopts="-kf @TSCHEDSTRUCT@ @TRANEXTRAOPTS@"
 ccopts=""
@@ -85,8 +115,8 @@ esac
 fatal=
 defaultlibraries=1
 
-
-# Options to occ21
+#}}}
+#{{{  options to occ21
 
 # Warnings:
 # -nwca : No warnings for CHAN OF ANY
@@ -139,10 +169,9 @@ case "$host_cpu" in
 		;;
 esac
 
-occ21=${OCC21:-occ21}
-octran=${OCTRAN:-$KROC/bin/tranx86}
-ocrtsdir=${OCRTSDIR:-$KROC/lib}
-ocrts=${OCRTS:--lkroc}
+
+#}}}
+#{{{  extra CC options
 
 # necessary for dynamic procs (makes all synbols appear in the dynamic symbol table)
 
@@ -156,6 +185,8 @@ case "$host_os" in
 esac
 
 
+#}}}
+#{{{  setup cc, as and ld
 cc=${CC:-gcc}
 as=${AS:-as}
 asflags=""
@@ -167,39 +198,14 @@ ldopts="-shared"
 # try A1=2, A=1 (powers rather than absolutes).
 asflags="$asflags --defsym A1=4 --defsym A2=2 -W"
 
-ocspath=
-if [ "X$OCSEARCH" != "X" ]; then
-  ocspath="$OCSEARCH:$ocrtsdir"
-else
-  ocspath="$ocrtsdir"
-fi
+#}}}
+#{{{  path temporaries build up from options
+opts_libs=""
+opts_libpaths=""
+opts_incpaths=""
+#}}}
 
-oclibpath=
-ocsearch=
-clincludepath=
-
-# ocspath is a COLON-SEPARATED list now, better process slightly differently
-
-
-XIFS="$IFS"
-IFS=':'
-
-for dir in $ocspath; do
-	dir=$(printf '%s' "$dir" | $SED -e 's:/$::')
-	oclibpath="$oclibpath -L$dir"
-	ocsearch="$ocsearch:$dir"
-	cincludepath="$cincludepath -I$dir"
-done
-
-IFS="$XIFS"
-
-# for dir in $ocspath; do
-# 	dir=$(printf '%s' "$dir" | $SED -e 's:/$::')
-# 	oclibpath="$oclibpath -L$dir"
-# 	ocsearch="$ocsearch $dir"
-# 	cincludepath="$cincludepath -I$dir"
-# done
-
+#{{{  various local settings
 use_occ21_revalt=1
 use_occ21_zen=1
 use_occ21_zep=1
@@ -228,6 +234,9 @@ usenocc=
 nocc="@NOCCHOME@/nocc"
 noccopts="--specs-file @NOCCHOME@/nocc.specs.xml"
 
+
+#}}}
+#{{{  process command-line arguments
 while :
 do
 	case $# in
@@ -243,12 +252,12 @@ do
 
 	# Split out the argument for options that take them
 	case $option in
-	--*=*)
+	--*=* | -C=*)
 		optarg=$(printf '%s' "$option" | $SED -e 's/^[^=]*=//')
 		;;
 	# These options have mandatory values.  Since we didn't find an = sign,
 	# the value must be in the next argument
-	--octran-opts | --oc-opts | --cc-opts | --nocc-opts)
+	--octran-opts | --oc-opts | --cc-opts | --nocc-opts | -C)
 		optarg=$1
 		shift
 		;;
@@ -256,233 +265,366 @@ do
 
 
 	case "$option" in
+		#{{{  -C <file>  configuration file
+	-C)
+		KROCCONFIG="$optarg"
+		printf '%s: using configuration from %s\n' "$progname" "$KROCCONFIG"
+		;;
+		#}}}
+		#{{{  -b, --brief  brief warnings
 	-b | --brief)
 		occopts="$occopts -b"
 		;;
+		#}}}
+		#{{{  -c, --compile  compile only
 	-c | --compile)
 		link=
 		octranopts="$octranopts -c"
 		noccopts="$noccopts -c"
 		;;
+		#}}}
+		#{{{  -e, --enable-udc  enable user-defined channel checks
 	-e | --enable-udc)
 		enable_udc=yes
 		# can't use enhanced enabling with UDCs
 		use_occ21_zen=0
 		;;
+		#}}}
+		#{{{  -p, --pre-compile  precompile sources
 	-p | --pre-compile)
 		translate=
 		link=
 		;;
+		#}}}
+		#{{{  -n, --dry-run  do dry-run
 	-n | --dry-run)
 		dorun=
 		verbose=yes
 		;;
+		#}}}
+		#{{{  --dryrun  dry-run (obsolete)
 	--dryrun)
 		dorun=
 	        printf '%s: --dryrun is obsolete, please use --dry-run\n' "$progname" 1>&2
 		verbose=yes
 		;;
+		#}}}
+		#{{{  --no-checks  disable run-time checks
 	--no-checks)
 		printf '%s: warning: disabling run-time checks\n' "$progname"
 		octranopts="$octranopts -n"
 		;;
+		#}}}
+		#{{{  -io, --inline-io  inline channel I/O
 	-io | --inline-io)
 		octranopts="$octranopts -ii -io -ia"
 		;;
+		#}}}
+		#{{{  -is, --inline-sched  inline scheduler operations
 	-is | --inline-sched)
 		octranopts="$octranopts -is"
 		;;
+		#}}}
+		#{{{  -it, --inline-ldtimer  inline timer operations
 	-it | --inline-ldtimer)
 		octranopts="$octranopts -it"
 		;;
+		#}}}
+		#{{{  -o  output file
 	-o)
 		outfile=$1
 		shift
 		;;
+		#}}}
+		#{{{  -o*  output file
 	-o*)
 		outfile=$(printf '%s' "$option" | $SED -e 's/^..//')
 		;;
+		#}}}
+		#{{{  -s, --strict  strict compilation mode
 	-s | --strict)
 		occopts="$occopts -strict"
 		;;
+		#}}}
+		#{{{  --oos  building for RMoX
 	--oos)
 		octranopts="$octranopts -ko"
 		;;
+		#}}}
+		#{{{  --nfw  no wait for globally FORKed processes
 	--nfw)
 		octranotps="$octranopts --nfw"
 		;;
+		#}}}
+		#{{{  --new  no external wait for blocking syscalls
 	--new)
 		octranopts="$octranopts --new"
 		;;
+		#}}}
+		#{{{  --octran-opts*  options for the translator
 	--octran-opts*)
 		octranopts="$octranopts $optarg"
 		;;
+		#}}}
+		#{{{  --oc-opts*  options for the occam compiler
 	--oc-opts*)
 		occopts="$occopts $optarg"
 		;;
+		#}}}
+		#{{{  --cc-opts*  options for the C compiler
 	--cc-opts*)
 		ccopts="$ccopts $optarg"
 		;;
+		#}}}
+		#{{{  --nocc-opts*  options for NOCC
 	--nocc-opts*)
 		noccopts="$noccopts $optarg"
 		;;
+		#}}}
+		#{{{  -nd, --no-dynmem  disable dynamic memory
 	-nd | --no-dynmem)
 		occopts="$occopts -ndm"
 		octranopts="$octranopts -nd"
 		;;
+		#}}}
+		#{{{  -l, --library  building dynamic library
 	-l | --library)
 		# set library (and non-main) for tranpc, and no vectorspace for compiler
 		octranopts="$octranopts -c -l"
 		occopts="$occopts -v"
 		makelib=yes
 		;;
+		#}}}
+		#{{{  -l*  adding library (arch-specific)
 	-l*)
-		ocllibs="$ocllibs $option"
+		opts_libs="$opts_libs $option"
 		;;
+		#}}}
+		#{{{  -L*  adding path to libraries
 	-L*)
 		dir=$(printf '%s' $option | $SED -e 's:/$::' -e 's:^..::')
-		oclibpath="-L$dir $oclibpath"
-		ocsearch="$dir:$ocsearch"
+		opts_libpaths="$dir:$opts_libpaths"
 		;;
+		#}}}
+		#{{{  -I*  adding path to includes
 	-I*)
 		dir=$(printf '%s' "$option" | $SED -e 's:/$::' -e 's:^..::')
-		ocsearch="$dir:$ocsearch"
-		cincludepath="-I$dir $cincludepath"
+		opts_incpaths="$dir:$opts_incpaths"
 		;;
+		#}}}
+		#{{{  -v, --verbose, --v, --verb*  verbose operation
 	-v | --verbose | --v | --verb*)
 		verbose=yes
 		octranopts="$octranopts -v"
 		;;
+		#}}}
+		#{{{  -k, --keep-temp  keep temporary files
 	-k | --keep-temp)
 		delete_temp=
 		octranopts="$octranopts -es"
 		;;
+		#}}}
+		#{{{  -V, --version  show version
 	-V | --version)
 		showversion=yes
 		;;
+		#}}}
+		#{{{  --libpath  show occam compiler library paths
 	--libpath)
 		showlibpath=yes
 		;;
+		#}}}
+		#{{{  --incpath  show occam compiler include paths
 	--incpath)
 		showincpath=yes
 		;;
+		#}}}
+		#{{{  --cclibpath  show C compiler library paths (-L...)
 	--cclibpath)
 		showlibpath=yes
 		showascc=yes
 		;;
+		#}}}
+		#{{{  --ccincpath  show C compiler include paths (-I...)
 	--ccincpath)
 		showincpath=yes
 		showascc=yes
 		;;
+		#}}}
+		#{{{  --cflags  show C compiler flags
 	--cflags)
 		showcflags=yes
 		;;
+		#}}}
+		#{{{  --cc  show C compiler
 	--cc)
 		showcc=yes
 		;;
+		#}}}
+		#{{{  --tranflags  show translator flags
 	--tranflags)
 		showtranflags=yes
 		;;
+		#}}}
+		#{{{  --tran  show path to translator
 	--tran)
 		showtran=yes
 		;;
+		#}}}
+		#{{{  -h, --help  show help
 	-h | --help | --he*)
 		fatal=yes
 		;;
+		#}}}
+		#{{{  -w, --warn  enable warnings
 	-w | --warn)
 		occwopts=$occ_warn_opts
 		;;
+		#}}}
+		#{{{  -nw, --no-warn  disable warnings
 	-nw | --no-warn)
 		occwopts=$occ_no_warn_opts
 		;;
+		#}}}
+		#{{{  -nowarn  no warnings (obsolete)
 	--nowarn)
 	        printf '%s: --nowarn is obsolete, please use --no-warn\n' "$progname" 1>&2
 		occwopts=$occ_no_warn_opts
 		;;
+		#}}}
+		#{{{  -t2, -t4, -t8, -t9  processor class
 	-t2 | -t4 | -t8 | -t9 )
 		proc_class=$(printf '%s' $option | $SED -e 's/^.//')
 		tsuffix="k$proc_class"
-	        printf '%s: Option $option is experimental: setting processor class to %s\n' "$progname" "$proc_class" 1>&2
+	        printf '%s: Option %s is experimental: setting processor class to %s\n' "$progname" "$option" "$proc_class" 1>&2
 		;;
+		#}}}
+		#{{{  -X1  enable ETC output (dummy)
 	-X1 )
 	        printf '%s: Already using ETC.  Ignorning.\n' "$progname" 1>&2
 		;;
+		#}}}
+		#{{{  -X2  enable user-defined operators (dummy)
 	-X2 )
 	        printf '%s: User defined operators already enabled.  Ignoring.\n' "$progname" 1>&2
 		;;
+		#}}}
+		#{{{  -X3  enable INITIAL decls (dummy)
 	-X3 )
 		printf '%s: INITIAL declarations already enabled.  Ignoring.\n' "$progname" 1>&2
 		;;
+		#}}}
+		#{{{  -X5  enable mobile types (dummy)
 	-X5 )
 		printf '%s: MOBILE types now enabled by default\n' "$progname" 1>&2
 		;;
+		#}}}
+		#{{{  -X6  enable extended input for unhandled CASE tags
 	-X6 )
 		printf '%s: enabling extended input for unhandled CASE tags\n' "$progname" 1>&2
 		occopts="$occopts -xtag"
 		;;
+		#}}}
+		#{{{  -X7  enable mobile processes
 	-X7 )
 		printf '%s: enabling mobile process types\n' "$progname" 1>&2
 		occopts="$occopts -mpt"
 		;;
+		#}}}
+		#{{{  -d  post-mortem debugging
 	-d )
 		printf '%s: Selecting post-mortem debugging\n' "$progname" 1>&2
 		octranopts="$octranopts -dX"
 		;;
+		#}}}
+		#{{{  -di  insert debugging
 	-di )
 		printf '%s: Selecting insert debugging\n' "$progname" 1>&2
 		octranopts="$octranopts -di"
 		;;
+		#}}}
+		#{{{  -dm  dynamic memory debugging
 	-dm )
 		printf '%s: Selecting dynamic memory debugging\n' "$progname" 1>&2
 		ocrtslibs="$ocrtslibs @DMOPTLIB@"
 		octranopts="$octranopts -dm"
 		;;
+		#}}}
+		#{{{  -ds  enable memory-usage summary
 	-ds )
 		printf '%s: Enabling memory usage summary\n' "$progname" 1>&2
 		octranopts="$octranopts -ds"
 		;;
+		#}}}
+		#{{{  -O, --optimise  enable optimisations (dummy)
 	-O | --optimise )
 		printf '%s: Optimisations already enabled\n' "$progname" 1>&2
 		;;
+		#}}}
+		#{{{  -P, --pause  enable scheduler-check at loopend
 	-P | --pause )
 		printf '%s: Enabling scheduler check at loop-end/back-jump\n' "$progname" 1>&2
 		octranopts="$octranopts -p"
 		;;
+		#}}}
+		#{{{  -S  stop error-mode
 	-S )
 		printf '%s: Compiling in STOP error mode\n' "$progname" 1>&2
 		octranopts="$octranopts -S"
 		;;
+		#}}}
+		#{{{  --force-tlp  force top-level interface to KYB, SCR, ERR
 	--force-tlp )
 		octranopts="$octranopts --tlp-kybscrerr"
 		;;
+		#}}}
+		#{{{  --skip-link  skip link into final exec.
 	--skip-link )
 		printf '%s: skipping final link into executable\n' "$progname" 1>&2
 		skip_link=yes
 		;;
+		#}}}
+		#{{{  --no-zen  no enhanced pre-enabling
 	--no-zen)
 		use_occ21_zen=0
 		;;
+		#}}}
+		#{{{  --use-zen  use enhanced pre-enabling
 	--use-zen)
 		use_occ21_zen=1
 		;;
+		#}}}
+		#{{{  --no-revalt  no reversed ALT disabling
 	--no-revalt)
 		use_occ21_revalt=0
 		;;
+		#}}}
+		#{{{  --use-revalt  use reversed ALT disabling
 	--use-revalt)
 		use_occ21_revalt=1
 		;;
+		#}}}
+		#{{{  --no-zep  no ALT preenabling
 	--no-zep)
 		use_occ21_zep=0
 		;;
+		#}}}
+		#{{{  --use-zep  use ALT pre-enabling
 	--use-zep)
 		use_occ21_zep=1
 		;;
+		#}}}
+		#{{{  --ncl  no compiler libraries
 	--ncl)
 		defaultlibraries=0
 		;;
+		#}}}
+		#{{{  --xml  dump XML
 	--xml)
 		dumpxml=1
 		;;
+		#}}}
+		#{{{  --nocc  use new occam-pi compiler
 	--nocc)
 		if [ ! -x $nocc ]; then
 			printf '%s: not configured to use NOCC\n' "$progname" 1>&2
@@ -490,21 +632,119 @@ do
 		fi
 		usenocc=1
 		;;
+		#}}}
+		#{{{  -z, --all-help  show all options
 	-z | --all-help)
 		showall=1
 		;;
+		#}}}
+		#{{{  --debugkroc  KRoC debugging enable (not for users)
 	--debugkroc)
 		debugkroc=1
 		;;
+		#}}}
+		#{{{  --*, -*  unrecognised options
 	--* | -*)
 		printf '%s: Unrecognized option: "%s"; use --help for usage.\n' "$progname" "$orig_option" 1>&2
 		exit 1
 		;;
+		#}}}
+		#{{{  *  source file
 	*)      srcs="$srcs $option"
 		;;
+		#}}}
 
 	esac
 done
+
+
+#}}}
+#{{{  source configuration
+
+if [ "$KROCCONFIG" = "" ]; then
+	# no configuration file found, use build/install defaults
+	kroc_archbindir="@KROC_ARCHBINDIR@"
+	kroc_archlibdir="@KROC_ARCHLIBDIR@"
+	kroc_archincdir="@KROC_ARCHINCDIR@"
+	kroc_mandir="@KROC_MANDIR@"
+	kroc_krocdir="@KROC_KROCDIR@"
+elif [ -r "$KROCCONFIG" ]; then
+	FAILEDSRC=0
+	source "$KROCCONFIG" 1> /dev/null 2>&1 || FAILEDSRC=1
+
+	if [ $FAILEDSRC -eq 1 ]; then
+		printf '%s: serious: failed to source configuration in %s\n' "$progname" "$KROCCONFIG"
+		exit 1
+	fi
+else
+	printf '%s: serious: cannot read configuration from %s\n' "$progname" "$KROCCONFIG"
+	exit 1
+fi
+
+		
+#}}}
+#{{{  path-dependant options
+
+occ21="$kroc_archbindir/occ21"
+octran="$kroc_archbindir/tranx86"
+ocrts="-lkroc"
+
+
+#}}}
+#{{{  build colon-separated search path for libraries
+ocspath=
+if [ "X$OCSEARCH" != "X" ]; then
+  ocspath="$OCSEARCH:$kroc_krocdir/vtlib:$kroc_krocdir/vtinclude"
+else
+  ocspath="$kroc_krocdir/vtlib:$kroc_krocdir/vtinclude"
+fi
+
+ocsearch=
+oclibpath="-L$kroc_archlibdir"
+cincludepath="-I$kroc_archincdir"
+
+
+#}}}
+#{{{  use "ocspath" to add entries to "oclibpath", "ocsearch" and "cincludepath"
+# ocspath is a COLON-SEPARATED list now, better process slightly differently
+
+
+XIFS="$IFS"
+IFS=':'
+
+for dir in $ocspath; do
+	dir=$(printf '%s' "$dir" | $SED -e 's:/$::')
+	ocsearch="$ocsearch:$dir"
+done
+
+IFS="$XIFS"
+
+#}}}
+#{{{  add given command-line entries to "oclibpath", "ocsearch" and "cincludepath"
+
+for lname in $opts_libs; do
+	ocllibs="$ocllibs $lname"
+done
+
+XIFS="$IFS"
+IFS=':'
+
+for dir in $opts_libpaths; do
+	oclibpath="-L$dir $oclibpath"
+	ocsearch="$dir:$ocsearch"
+done
+
+for dir in $opts_incpaths; do
+	cincludepath="-I$dir $cincludepath"
+	ocsearch="$dir:$ocsearch"
+done
+
+IFS="$XIFS"
+
+#}}}
+
+
+#{{{  set extra flags from options
 
 if [ $use_occ21_revalt -eq 1 ]; then
 	occopts="$occopts -revalt"
@@ -520,12 +760,16 @@ if [ $defaultlibraries -eq 1 ]; then
 	ocllibs="-loccam8 -loccamutl $ocllibs"
 fi
 
-# Add current directory first, always
+#}}}
+#{{{  add current directory as first in search paths
 oclibpath="-L. $oclibpath"
 ocsearch=".:$ocsearch"
 cincludepath="-I. $cincludepath"
 procopts="-$proc_class"
 occopts="$procopts $occopts"
+
+#}}}
+#{{{  add flags for user-defined channels if enabled
 
 if [ $enable_udc ]; then
 	# enable MOBILE size-field
@@ -536,14 +780,20 @@ else
 	octranopts="$octranopts -nec"
 fi
 
+#}}}
+#{{{  show library paths and exit if requested
+
 if [ $showlibpath ]; then
 	if [ $showascc ]; then
 		printf '%s\n' "$oclibpath"
 	else
-		printf '%s\n' "$oclibpath" | $SED -e 's:-L::g' -e 's/ /:/g' -e 's/::/:/g'
+		printf '%s\n' "$ocsearch" | $SED -e 's:^ ::g' -e 's: $::g' -e 's/ /:/g' -e 's/::/:/g'
 	fi
 	exit 0
 fi
+
+#}}}
+#{{{  show include paths and exit if requested
 
 if [ $showincpath ]; then
 	if [ $showascc ]; then
@@ -553,6 +803,9 @@ if [ $showincpath ]; then
 	fi
 	exit 0
 fi
+
+#}}}
+
 
 if [ $showcflags ]; then
 	printf '%s\n' "$extcflags"
@@ -590,12 +843,12 @@ if [ "X${fatal}" != "X" -o "X$srcs" = "X" -o "X$showversion" != "X" ]; then
 		showversion=yes
 	fi
 	if [ $showversion ]; then
-		cat $KROC/AUTHORS
+		cat $kroc_krocdir/doc/AUTHORS
 		exit 0
 	fi
 
 	exec 1>&2
-	printf 'Usage: %s [options] [occam sources/pre-compiled sources]\n' "$progname"
+	printf 'Usage: %s [-C config-file] [options] [occam sources/pre-compiled sources]\n' "$progname"
 	cat << EOF
 Options:
   -b,  --brief           Give brief occ21 error messages
@@ -827,7 +1080,7 @@ for src in $srcs; do
 	if [ $verbose ]; then
 		printf '%s: Search path for native libraries:\n' "$progname" 1>&2
 		printf '  %s\n' "$oclibpath" | $SED -e 's:-L::g' 1>&2
-		printf '%s: Search path for occam libraries and includes; C headers:\n' "$progname" 1>&2
+		printf '%s: Search path for occam libraries and includes:\n' "$progname" 1>&2
 		printf '  %s\n' "$ocsearch" 1>&2
 	fi
 
